# Generated by Django 3.1.1 on 2020-10-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripHelpmate', '0007_auto_20201015_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantrip',
            old_name='trip',
            new_name='trips',
        ),
    ]
