# Generated by Django 3.1.1 on 2020-10-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TripHelpmate", "0008_auto_20201015_1324"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantrip",
            old_name="trips",
            new_name="trip",
        ),
    ]
