# Generated by Django 3.1.1 on 2020-10-17 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TripHelpmate', '0012_auto_20201016_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='default_pic.jpg', upload_to='user_pics')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TripHelpmate.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
