# Generated by Django 3.1.1 on 2020-10-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TripHelpmate", "0013_imggallery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imggallery",
            name="trip",
        ),
        migrations.AlterField(
            model_name="imggallery",
            name="picture",
            field=models.ImageField(
                default="default_pic.jpg", upload_to="uploadmodel_file_upload_to"
            ),
        ),
    ]
